
Vagrant.configure("2") do |config|

'
  (0..2).each do |i|
    config.vm.define "master-#{i}" do |master|
      master.vm.box = "centos/7"
      master.vm.hostname = "master-#{i}"
      master.vm.network "private_network", ip: "192.168.33.1#{i}"
    end
  end
'
  config.vm.define "master-0" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master-0"
    master.vm.network "private_network", ip: "192.168.33.10"
  end

'
  (0..2).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      master.vm.box = "centos/7"
      master.vm.hostname = "worker-#{i}"
      master.vm.network "private_network", ip: "192.168.33.2#{i}"
    end
  end
'
  config.vm.define "worker-0" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "worker-0"
    master.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2000"
    vb.cpus = 2
  end

  config.vm.provision "file", source: "keys/key.pub", destination: "$HOME/.ssh/authorized_keys"
  
end
