
Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "master-debian-test" do |test1|
    test1.vm.box = "centos/7"
    test1.vm.hostname = "master-debian-test"
    test1.vm.network "private_network", ip: "192.168.33.11"
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 12
  end

  config.vm.provision "file", source: "keys/key.pub", destination: "$HOME/.ssh/authorized_keys"
  
end
