---
# tasks file for kubeadm-init
- name: Check kubeconfig status
  stat:
    path: /home/vagrant/.kube
  register: kubernetes_status
- name: Disable swap
  command: swapoff -a
- name: Cluster Init 
  block:
  - name: Generate Kubeadm Certificate Key
    command: kubeadm certs certificate-key
    register: certificate_key
  - name: Initialize the Kubernetes Cluster with kubeadm
    command: kubeadm init {{ controlplane_ha }} --pod-network-cidr=192.168.0.0/16 --upload-certs --certificate-key {{ certificate_key.stdout }} --apiserver-advertise-address {{ ansible_host }}  
  - name: Create a directory for Kubernetes Cluster configuration
    become_user: vagrant
    file:
      path: ~/.kube
      state: directory
  - name: Copy file with cluster config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant
  - name: Generate Discovery Token CA Hash
    shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
    register: token_hash
  - name: Select Token 
    shell: kubeadm token list | awk '{if ($13 == "system:bootstrappers:kubeadm:default-node-token")  print $1}'
    register: token 
  - name: Install Calico
    command: kubectl create -f {{ item }}
    loop:
      - https://docs.projectcalico.org/manifests/tigera-operator.yaml
      - https://docs.projectcalico.org/manifests/custom-resources.yaml
    become_user: vagrant
  when: not kubernetes_status.stat.exists and inventory_hostname == 'master-0'
- name: Join master nodes to Control plane 
  block:
  - name: Join master nodes to Control Plane
    command: kubeadm join 172.18.0.1:6443 --token {{ hostvars['master-0']['token'].stdout }} --discovery-token-ca-cert-hash sha256:{{ hostvars['master-0']['token_hash'].stdout }} --control-plane --certificate-key {{ hostvars['master-0']['certificate_key'].stdout }} --apiserver-advertise-address {{ ansible_host }}
  - name: Create a directory for Kubernetes Cluster configuration
    become_user: vagrant
    file:
      path: ~/.kube
      state: directory
  - name: Copy file with cluster config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: yes
      owner: vagrant
      group: vagrant
  when: inventory_hostname == 'master-1' or inventory_hostname == 'master-2'
- name: Join Worker nodes
  command: kubeadm join {{ controlplane_ip }}:6443 --token {{ hostvars['master-0']['token'].stdout }} --discovery-token-ca-cert-hash sha256:{{ hostvars['master-0']['token_hash'].stdout }} 
  when: ansible_hostname in groups['workers']
- name: Gather configuration
  shell: cat /var/lib/kubelet/kubeadm-flags.env | cut -d '"' -f 2
  register: kubelet_vars
- name: Edit Config 
  shell: echo 'KUBELET_KUBEADM_ARGS="{{ kubelet_vars.stdout }} --node-ip={{ ansible_host }}"' >  /var/lib/kubelet/kubeadm-flags.env
- name: Restart Docker
  systemd:
    state: restarted
    name: kubelet
    daemon_reload: yes
    enabled: yes

 
 