---
# tasks file for kubeadm-init
- name: Check kubeconfig status
  stat:
    path: /home/"{{ ansible_user }}"/.kube
  register: kubernetes_status
- name: Disable swap
  command: swapoff -a
- name: Cluster Init 
  block:
  - name: Generate Kubeadm Certificate Key
    command: kubeadm certs certificate-key
    register: certificate_key
  - name: Initialize the Kubernetes Cluster with kubeadm
    command: kubeadm init {{ controlplane_ha }} --pod-network-cidr=192.168.0.0/16 --upload-certs --certificate-key {{ certificate_key.stdout }} --apiserver-advertise-address {{ node_ip }}  
  - name: Create a directory for Kubernetes Cluster configuration
    become_user: "{{ ansible_user }}"
    file:
      path: ~/.kube
      state: directory
  - name: Copy file with cluster config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "/home/{{ ansible_user }}/.kube/config"
      remote_src: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: Generate Discovery Token CA Hash
    shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
    register: token_hash
  - name: Select Token 
    shell: kubeadm token list | awk '{if ($13 == "system:bootstrappers:kubeadm:default-node-token")  print $1}'
    register: token 
  - name: Install Calico
    command: kubectl create -f {{ item }}
    loop:
      - https://docs.projectcalico.org/manifests/tigera-operator.yaml
      - https://docs.projectcalico.org/manifests/custom-resources.yaml
    become_user: "{{ ansible_user }}"
  when: not kubernetes_status.stat.exists and ('master-0' in inventory_hostname)
- name: Join master nodes to Control plane 
  block:
  - name: Join master nodes to Control Plane
    command: kubeadm join 172.18.0.1:6443 --token {{ hostvars['master-0']['token'].stdout }} --discovery-token-ca-cert-hash sha256:{{ hostvars['master-0']['token_hash'].stdout }} --control-plane --certificate-key {{ hostvars['master-0']['certificate_key'].stdout }} --apiserver-advertise-address {{ node_ip }}
  - name: Create a directory for Kubernetes Cluster configuration
    become_user: "{{ ansible_user }}"
    file:
      path: ~/.kube
      state: directory
  - name: Copy file with cluster config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/"{{ ansible_user }}"/.kube/config
      remote_src: yes
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  when: ('master-1' in inventory_hostname) or ('master-2' in inventory_hostname)
- name: Join Worker nodes Vagrant
  command: kubeadm join {{ controlplane_ip }}:6443 --token {{ hostvars['master-0']['token'].stdout }} --discovery-token-ca-cert-hash sha256:{{ hostvars['master-0']['token_hash'].stdout }} 
  register: vagrant_join
  when: (ansible_host == "192.168.33.20") or (ansible_host == "192.168.33.21") or (ansible_host == "192.168.33.22")
- name: Join Worker nodes AWS
  command: kubeadm join {{ hostvars['Name_iac-micro-default-master-0']['node_ip'] }}:6443 --token {{ hostvars['Name_iac-micro-default-master-0']['token'].stdout }} --discovery-token-ca-cert-hash sha256:{{ hostvars['Name_iac-micro-default-master-0']['token_hash'].stdout }} 
  when: inventory_hostname in groups['workers'] and not vagrant_join.changed
- name: Gather configuration
  shell: cat /var/lib/kubelet/kubeadm-flags.env | cut -d '"' -f 2
  register: kubelet_vars
- name: Edit Config 
  shell: echo 'KUBELET_KUBEADM_ARGS="{{ kubelet_vars.stdout }} --node-ip={{ node_ip }}"' >  /var/lib/kubelet/kubeadm-flags.env
- name: Restart Docker
  systemd:
    state: restarted
    name: kubelet
    daemon_reload: yes
    enabled: yes

 
 