plugin: aws_ec2
regions:
  - us-east-1
hostnames:
  - tag:Name=iac-micro-default-master-0
  - tag:Name=iac-micro-default-master-1
  - tag:Name=iac-micro-default-master-2
  - tag:Name=iac-micro-default-worker-0
  - tag:Name=iac-micro-default-worker-1
  - tag:Name=iac-micro-default-worker-2
groups:
  controlplane: "'master' in (inventory_hostname)"
  workers: "'worker' in (inventory_hostname)"
compose:
  node_ip: private_ip_address
  ansible_host: public_ip_address