- hosts: all
  become: yes
  tasks:
  - name: Reset kubeadm install
    command: kubeadm reset -f
    register: rollback_nodes
  - name: Delete Kubernetes Cluster configuration
    become_user: vagrant
    file:
      path: ~/.kube
      state: absent