all:
  children:
    controlplane:
      hosts:
        master-0:
          ansible_host: 192.168.33.10
        master-1:
          ansible_host: 192.168.33.11
        master-2:
          ansible_host: 192.168.33.12
    workers:
      hosts:
        worker-0:
          ansible_host: 192.168.33.20
        worker-1:
          ansible_host: 192.168.33.21
        worker-2:
          ansible_host: 192.168.33.22
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ../vagrant/keys/key